#!/bin/bash

homalg_modules="AbelianSystems alexander AlgebraicThomas AutoDoc Blocks CategoriesForHomalg Conley D-Modules ExamplesForHomalg Gauss GaussForHomalg GradedModules GradedRingForHomalg homalg HomalgToCAS IO_ForHomalg k-Points LessGenerators LetterPlace LocalizeRingForHomalg MapleForHomalg MatricesForHomalg Modules RingsForHomalg Orbifolds PrimaryDecomposition SCO SCSCP_ForHomalg Sheaves SimplicialObjects SingularForHomalg SystemTheory ToolsForHomalg VirtualCAS CombinatoricsForHomalg test_suite ToricVarieties"
years="2006 2007 2008 2009 2010 2011 2012 2013 2014 2015"
months="1 2 3 4 5 6 7 8 9 10 11 12"

rm -rf repos

mkdir repos

for i in $homalg_modules; do git clone git@github.com:homalg-project/${i}.git repos/${i}; done

for i in $homalg_modules; do cd repos/${i}; git commit --allow-empty -m "Update"; cd ../..; done

echo "Stats" > stats_authors.csv
echo "Month,Number of authors;" >> stats_authors.csv

echo "Author names" > stats_names.csv
echo "Month,Names;" >> stats_names.csv

for year in $years; do
  for month in $months; do
    echo "Current hashes" > hashes.txt
    touch current_authors.txt
    for i in $homalg_modules; do
      cd repos/${i}
      master_hash=$(git rev-parse HEAD)
      git checkout `git rev-list -n 1 --before="${year}-${month}-01" master` 1>/dev/null 2>&1
      hash=$(git rev-parse HEAD)
      if [ "$master_hash" = "$hash" ]; then
        echo "${i} was not there in ${year}/${month}"
      else
        Y=$(cat ../../hashes.txt | grep ${hash} )
        if [ "$Y" = "" ]; then
          packages=$(($packages+1))
          echo $hash >> ../../hashes.txt
          git log --format='%aN' | sort -u >> ../../current_authors.txt
        else
          echo "${i} was already equal to another repo"
        fi
      fi
      git checkout master 1>/dev/null 2>&1
      cd ../..
    done
    cat current_authors.txt | sort -u > current_authors_clean.txt
    rm current_authors.txt
    echo "${year}-${month},$(cat current_authors_clean.txt | wc -l);" >> stats_authors.csv
    echo "${year}-${month},$(tr '\n' ' ' < current_authors_clean.txt);" >> stats_names.csv
  done
done

